# project files
PROJECT  := nvme_bw

CFILES   := $(PROJECT).c
DEPFILES :=


# basic configuration
dbg      :=
shared   :=

jni      :=
ibv      :=
spdk     := 1

myrdma   :=
mynvme   :=

u2       :=

include ../../../../mk/common.mk
