# project files
PROJECT  := libjninvme

CFILES   := jninvme.c
DEPFILES :=

# basic configuration
dbg      :=
shared   := 1

jni      := 1
ibv      :=
spdk     := 1

myrdma   :=
mynvme   :=

u2       :=

include ../../../../mk/common.mk
